{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000278D7AD90F0>: Failed to resolve 'thetestingworldapi.comapi' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='thetestingworldapi.comapi', port=443): Max retries exceeded with url: /technicalskills (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000278D7AD90F0>: Failed to resolve 'thetestingworldapi.comapi' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='thetestingworldapi.comapi', port=443): Max retries exceeded with url: /technicalskills (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000278D7AD90F0>: Failed to resolve 'thetestingworldapi.comapi' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_add_new_data", "rerun": "0"}}, "suite_name": "StudentMS/test_end_to_end_test.py"}}}, "date": "August 21, 2023", "start_time": 1692647491.4396527, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}